CREATE TABLE STATEMENT_RECORDS (
    REFERENCE NUMERIC(6) PRIMARY KEY,
    ACCOUNT_NUMBER VARCHAR(18),
    DESCRIPTION VARCHAR(100),
    START_BALANCE DECIMAL(10, 2),
    MUTATION DECIMAL(10, 2),
    END_BALANCE DECIMAL(10, 2)
);